// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// DashboardData holds the data needed to render the dashboard page.
type DashboardData struct {
	StoreJSON string // JSON blob for Alpine.store('drives') hydration
}

func Dashboard(data DashboardData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(`<script>
document.addEventListener('alpine:init', () => {
	Alpine.store('drives', %s)

	const evtSource = new EventSource('/events')
	evtSource.addEventListener('drive-update', (e) => {
		const update = JSON.parse(e.data)
		Alpine.store('drives').ready = update.ready
		Alpine.store('drives').list = update.list
	})
})
</script>`, data.StoreJSON)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"page-header\"><h1>Drives</h1></div><div class=\"drive-grid\" x-data><template x-if=\"!$store.drives.ready\"><div class=\"empty-state\"><p>Scanning for drives…</p></div></template><template x-if=\"$store.drives.ready && $store.drives.list.length === 0\"><div class=\"empty-state\"><p>No drives detected. Make sure MakeMKV is installed and a drive is connected.</p></div></template><template x-for=\"drive in $store.drives.list\" :key=\"drive.index\"><div class=\"card\" :id=\"'drive-' + drive.index\"><div class=\"card-header\"><span class=\"card-title\" x-text=\"drive.name\"></span> <span :class=\"'badge badge-' + drive.state\" x-text=\"drive.state\"></span></div><template x-if=\"drive.discName\"><p class=\"text-secondary\" x-text=\"drive.discName\"></p></template><template x-if=\"!drive.discName\"><p class=\"text-muted\">No disc</p></template><template x-if=\"drive.discName\"><div class=\"mt-3\"><a :href=\"'/drives/' + drive.index\" class=\"btn btn-secondary btn-sm\">Details</a></div></template></div></template></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
