// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

// DriveDetailData holds all data needed to render the drive detail page.
type DriveDetailData struct {
	DriveIndex int
	DriveName  string
	DiscName   string
	State      string
	Error      string
	StoreJSON  string // JSON blob for Alpine.store('drive') hydration
	CSRFToken  string
}

func DriveDetail(data DriveDetailData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(`<script>
document.addEventListener('alpine:init', () => {
	Alpine.store('drive', %s)

	const evtSource = new EventSource('/events')

	evtSource.addEventListener('scan-complete', (e) => {
		const update = JSON.parse(e.data)
		if (update.driveIndex === Alpine.store('drive').driveIndex) {
			Alpine.store('drive').scanning = false
			Alpine.store('drive').titles = update.titles
		}
	})

	evtSource.addEventListener('drive-event', (e) => {
		const update = JSON.parse(e.data)
		if (update.DriveIndex === Alpine.store('drive').driveIndex) {
			Alpine.store('drive').state = update.State
			Alpine.store('drive').discName = update.DiscName
			if (update.Type === 'disc_ejected') {
				Alpine.store('drive').titles = []
				Alpine.store('drive').selectedRelease = null
				Alpine.store('drive').searchResults = []
				Alpine.store('drive').scanning = false
			}
		}
	})

	evtSource.addEventListener('rip-update', (e) => {
		const update = JSON.parse(e.data)
		if (update.DriveIndex === Alpine.store('drive').driveIndex) {
			Alpine.store('drive').ripProgress = update
		}
	})
})

async function searchDiscDB(driveIndex) {
	const query = document.getElementById('search-query').value.trim()
	if (!query) return

	const form = new FormData()
	form.append('query', query)

	const resp = await fetch('/drives/' + driveIndex + '/search', {
		method: 'POST',
		headers: { 'Accept': 'application/json' },
		body: form,
	})

	if (resp.ok) {
		Alpine.store('drive').searchResults = await resp.json()
	}
}

async function selectRelease(driveIndex, result) {
	Alpine.store('drive').selectedRelease = {
		mediaItemID: result.mediaItemID,
		releaseID: result.releaseID,
		title: result.mediaTitle,
		year: String(result.mediaYear),
		type: result.mediaType,
	}

	const resp = await fetch('/drives/' + driveIndex + '/select', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
			'Accept': 'application/json',
		},
		body: JSON.stringify({
			mediaItemID: result.mediaItemID,
			releaseID: result.releaseID,
			title: result.mediaTitle,
			year: String(result.mediaYear),
			type: result.mediaType,
		}),
	})

	if (resp.ok) {
		const data = await resp.json()
		Alpine.store('drive').scanning = data.scanning
		if (data.titles && data.titles.length > 0) {
			Alpine.store('drive').titles = data.titles
		}
	}
}
</script>`, data.StoreJSON)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Error != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"alert alert-error\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Error)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/drive_detail.templ`, Line: 108, Col: 16}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <div class=\"page-header\"><h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.DriveName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/drive_detail.templ`, Line: 113, Col: 23}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h1><a href=\"/\" class=\"btn btn-secondary btn-sm\">← Back</a></div><!-- Disc Info Card --> <div class=\"card\" style=\"margin-bottom: 1rem;\"><div class=\"card-header\"><span class=\"card-title\">Disc Info</span> <span x-data :class=\"'badge badge-' + $store.drive.state\" x-text=\"$store.drive.state\"></span></div><p class=\"text-secondary\" x-data x-text=\"$store.drive.discName\"></p></div><!-- Search Card --> <div class=\"card\" style=\"margin-bottom: 1rem;\" x-data><div class=\"section-title\">Search TheDiscDB</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(`<form x-on:submit.prevent="searchDiscDB(%d)">
				<div class="flex gap-2 items-center">
					<input type="search" id="search-query" placeholder="Search by title, UPC, ASIN…"
						x-init="$el.value = $store.drive.discName"
						style="flex:1;"/>
					<button type="submit" class="btn btn-primary btn-sm">Search</button>
				</div>
			</form>`, data.DriveIndex)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Search Results --><div class=\"mt-3\"><template x-if=\"$store.drive.searchResults.length > 0\"><div style=\"overflow-x:auto;\"><table><thead><tr><th>Title</th><th>Year</th><th>Type</th><th>Release</th><th>UPC</th><th>Format</th><th></th></tr></thead> <tbody><template x-for=\"r in $store.drive.searchResults\" :key=\"r.releaseID\"><tr><td x-text=\"r.mediaTitle\"></td><td class=\"text-secondary\" x-text=\"r.mediaYear\"></td><td><span class=\"badge badge-identified\" x-text=\"r.mediaType\"></span></td><td class=\"text-secondary\" x-text=\"r.releaseTitle\"></td><td class=\"text-muted\" x-text=\"r.releaseUPC\"></td><td class=\"text-secondary\" x-text=\"r.format\"></td><td>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(`<button class="btn btn-primary btn-sm" x-on:click="selectRelease(%d, r)">Select</button>`, data.DriveIndex)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</td></tr></template></tbody></table></div></template></div></div><!-- Saved Mapping Banner (from previous rip) --> <template x-data x-if=\"$store.drive.hasMapping && !$store.drive.selectedRelease\"><div class=\"card\" style=\"margin-bottom: 1rem;\"><div class=\"alert alert-success\" style=\"display:flex; justify-content:space-between; align-items:center;\"><span>Matched: <span x-text=\"$store.drive.matchedMedia\"></span></span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.Raw(fmt.Sprintf(`<a href="/drives/%d/rescan" class="btn btn-secondary btn-sm">Re-scan</a>`, data.DriveIndex)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></template><!-- Matched Release Banner (from current session selection) --> <template x-data x-if=\"$store.drive.selectedRelease\"><div class=\"card\" style=\"margin-bottom: 1rem;\"><div class=\"alert alert-success\">Matched: <span x-text=\"$store.drive.selectedRelease.title\"></span> (<span x-text=\"$store.drive.selectedRelease.year\"></span>) — <span x-text=\"$store.drive.selectedRelease.type\"></span></div></div></template><!-- Titles Card --> <div class=\"card\" x-data><div class=\"section-title\">Titles</div><template x-if=\"$store.drive.scanning\"><div class=\"empty-state\"><p>Scanning disc…</p></div></template><template x-if=\"!$store.drive.scanning && $store.drive.titles.length === 0\"><div class=\"empty-state\"><p>No titles found. Insert a disc or wait for scanning to complete.</p></div></template><template x-if=\"!$store.drive.scanning && $store.drive.titles.length > 0\"><form hx-post=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/drives/%d/rip", data.DriveIndex))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/drive_detail.templ`, Line: 213, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" hx-target=\"body\" hx-swap=\"outerHTML\"><input type=\"hidden\" name=\"_csrf\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.CSRFToken)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/drive_detail.templ`, Line: 214, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"><!-- Hidden fields populated from Alpine store --><input type=\"hidden\" name=\"disc_name\" x-bind:value=\"$store.drive.discName\"> <input type=\"hidden\" name=\"media_item_id\" x-bind:value=\"$store.drive.selectedRelease ? $store.drive.selectedRelease.mediaItemID : ''\"> <input type=\"hidden\" name=\"release_id\" x-bind:value=\"$store.drive.selectedRelease ? $store.drive.selectedRelease.releaseID : ''\"> <input type=\"hidden\" name=\"content_title\" x-bind:value=\"$store.drive.selectedRelease ? $store.drive.selectedRelease.title : ''\"> <input type=\"hidden\" name=\"content_year\" x-bind:value=\"$store.drive.selectedRelease ? $store.drive.selectedRelease.year : ''\"> <input type=\"hidden\" name=\"content_type\" x-bind:value=\"$store.drive.selectedRelease ? $store.drive.selectedRelease.type : ''\"><div style=\"overflow-x:auto;\"><table><thead><tr><th></th><th>#</th><th>Name</th><th>Duration</th><th>Size</th></tr></thead> <tbody><template x-for=\"t in $store.drive.titles\" :key=\"t.index\"><tr><td><input type=\"checkbox\" name=\"titles\" :value=\"t.index\" :checked=\"t.selected\"></td><td class=\"text-muted\" x-text=\"t.index\"></td><td x-text=\"t.name\"></td><td class=\"text-secondary\" x-text=\"t.duration\"></td><td class=\"text-secondary\" x-text=\"t.size\"></td></tr></template></tbody></table></div><div class=\"mt-3\"><button type=\"submit\" class=\"btn btn-primary\">Rip Selected</button></div></form></template></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(data.DiscName).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
