package aacs

import (
	"os"
	"path/filepath"
	"testing"
)

// --- fixture builders -------------------------------------------------------
//
// Payload bytes are generated by a deterministic LCG with 0x47 filtered out, so
// a sync lock in a test fixture is never accidental: every 0x47 in these files
// was placed on purpose.

func payloadBytes(seed uint32, n int) []byte {
	out := make([]byte, n)
	s := seed | 1
	for i := range out {
		s = s*1664525 + 1013904223
		b := byte(s >> 24)
		if b == syncByte {
			b = 0x46
		}
		out[i] = b
	}
	return out
}

// cipherBytes is like payloadBytes but does not filter 0x47 — it stands in for
// AACS ciphertext, where a stray sync byte is possible but a run of them at a
// fixed stride is not.
func cipherBytes(seed uint32, n int) []byte {
	out := make([]byte, n)
	s := seed | 1
	for i := range out {
		s = s*1664525 + 1013904223
		out[i] = byte(s >> 24)
	}
	return out
}

// buildM2TS produces a BDAV-style stream: 4-byte TP_extra_header followed by a
// 188-byte TS packet, giving a 192-byte stride with sync at offset 4.
func buildM2TS(packets int, tsc byte) []byte {
	out := make([]byte, 0, packets*m2tsPacketSize)
	for i := 0; i < packets; i++ {
		out = append(out, payloadBytes(uint32(i)+1, 4)...) // TP_extra_header
		out = append(out, syncByte)
		out = append(out, 0x01, 0x00)  // PID etc.
		out = append(out, tsc<<6|0x10) // scrambling control in top 2 bits
		out = append(out, payloadBytes(uint32(i)+7, tsPacketSize-4)...)
	}
	return out
}

// buildTS188 produces a plain transport stream: 188-byte stride, sync at 0.
func buildTS188(packets int, tsc byte) []byte {
	out := make([]byte, 0, packets*tsPacketSize)
	for i := 0; i < packets; i++ {
		out = append(out, syncByte)
		out = append(out, 0x01, 0x00)
		out = append(out, tsc<<6|0x10)
		out = append(out, payloadBytes(uint32(i)+11, tsPacketSize-4)...)
	}
	return out
}

// buildAACSEncrypted models a genuinely AACS-protected stream: 6144-byte
// aligned units whose first 16 bytes are plaintext and whose remainder is
// ciphertext. Only the first packet of each unit has a readable sync byte.
func buildAACSEncrypted(units int) []byte {
	out := make([]byte, 0, units*alignedUnitSize)
	for i := 0; i < units; i++ {
		head := make([]byte, 0, 16)
		head = append(head, payloadBytes(uint32(i)+3, 4)...) // TP_extra_header
		head = append(head, syncByte)
		head = append(head, 0x01, 0x00, 0x10)
		head = append(head, payloadBytes(uint32(i)+5, 8)...)
		out = append(out, head...)
		out = append(out, cipherBytes(uint32(i)+101, alignedUnitSize-16)...)
	}
	return out
}

// writeDisc lays out a disc root containing a single stream file.
func writeDisc(t *testing.T, data []byte, withAACS bool) string {
	t.Helper()
	root := t.TempDir()
	streamDir := filepath.Join(root, "BDMV", "STREAM")
	if err := os.MkdirAll(streamDir, 0o777); err != nil {
		t.Fatalf("mkdir stream dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(streamDir, "00000.m2ts"), data, 0o666); err != nil {
		t.Fatalf("write m2ts: %v", err)
	}
	if withAACS {
		if err := os.MkdirAll(filepath.Join(root, "AACS"), 0o777); err != nil {
			t.Fatalf("mkdir aacs: %v", err)
		}
		if err := os.WriteFile(filepath.Join(root, "AACS", "Unit_Key_RO.inf"), []byte("x"), 0o666); err != nil {
			t.Fatalf("write aacs file: %v", err)
		}
	}
	return root
}

// enoughPackets is sized so every sample offset gets a full run of packets.
const enoughPackets = sampleCount * packetsPerSample * 3

// --- tests ------------------------------------------------------------------

func TestInspectStreamsUnencryptedM2TS(t *testing.T) {
	root := writeDisc(t, buildM2TS(enoughPackets, 0), true)

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictUnencrypted {
		t.Fatalf("Verdict = %q, want %q (reason: %s)", got.Verdict, VerdictUnencrypted, got.Reason)
	}
	if got.Stride != m2tsPacketSize {
		t.Errorf("Stride = %d, want %d", got.Stride, m2tsPacketSize)
	}
	if got.ScrambledPackets != 0 {
		t.Errorf("ScrambledPackets = %d, want 0", got.ScrambledPackets)
	}
	if got.PacketsChecked < minPacketsChecked {
		t.Errorf("PacketsChecked = %d, want >= %d", got.PacketsChecked, minPacketsChecked)
	}
}

// A 188-byte stride must also be handled: the original investigation notes
// assumed this layout, and some sources really are plain .ts.
func TestInspectStreamsUnencrypted188Stride(t *testing.T) {
	root := writeDisc(t, buildTS188(enoughPackets, 0), false)

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictUnencrypted {
		t.Fatalf("Verdict = %q, want %q (reason: %s)", got.Verdict, VerdictUnencrypted, got.Reason)
	}
	if got.Stride != tsPacketSize {
		t.Errorf("Stride = %d, want %d", got.Stride, tsPacketSize)
	}
}

// The scrambling bits are the top two of byte 3. A detector that masked with
// 0x03 before shifting would report every one of these as clear.
func TestInspectStreamsScramblingBitsSet(t *testing.T) {
	for _, tsc := range []byte{0x01, 0x02, 0x03} {
		root := writeDisc(t, buildM2TS(enoughPackets, tsc), true)

		got, err := InspectStreams(root)
		if err != nil {
			t.Fatalf("tsc=%d InspectStreams: %v", tsc, err)
		}
		if got.Verdict != VerdictScrambled {
			t.Errorf("tsc=%d Verdict = %q, want %q", tsc, got.Verdict, VerdictScrambled)
		}
		if got.ScrambledPackets == 0 {
			t.Errorf("tsc=%d ScrambledPackets = 0, want > 0", tsc)
		}
	}
}

// On a genuinely AACS-encrypted disc most sync bytes are themselves ciphertext,
// so no stride lock is possible. Sync surviving at each 6144-byte aligned-unit
// boundary is what identifies it — and it must never read as unencrypted.
func TestInspectStreamsAACSAlignedUnits(t *testing.T) {
	root := writeDisc(t, buildAACSEncrypted(600), true)

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictScrambled {
		t.Fatalf("Verdict = %q, want %q (reason: %s)", got.Verdict, VerdictScrambled, got.Reason)
	}
}

func TestInspectStreamsNoSyncAnywhere(t *testing.T) {
	root := writeDisc(t, cipherBytes(9, 4*1024*1024), true)

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictUnknown {
		t.Errorf("Verdict = %q, want %q", got.Verdict, VerdictUnknown)
	}
}

// Too little data to sample is an inconclusive result, never a green light.
func TestInspectStreamsTruncatedFile(t *testing.T) {
	root := writeDisc(t, buildM2TS(10, 0), true)

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictUnknown {
		t.Errorf("Verdict = %q, want %q", got.Verdict, VerdictUnknown)
	}
}

// DVDs have no BDMV/STREAM. They use CSS, not AACS, and must no-op.
func TestInspectStreamsNoStreamDir(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "VIDEO_TS"), 0o777); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if got.Verdict != VerdictNotApplicable {
		t.Errorf("Verdict = %q, want %q", got.Verdict, VerdictNotApplicable)
	}
}

// The largest stream is the feature; small ones are menus and trailers that may
// not be representative.
func TestInspectStreamsPicksLargestFile(t *testing.T) {
	root := t.TempDir()
	streamDir := filepath.Join(root, "BDMV", "STREAM")
	if err := os.MkdirAll(streamDir, 0o777); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(streamDir, "00001.m2ts"), buildM2TS(20, 0), 0o666); err != nil {
		t.Fatalf("write small: %v", err)
	}
	if err := os.WriteFile(filepath.Join(streamDir, "00002.m2ts"), buildM2TS(enoughPackets, 0), 0o666); err != nil {
		t.Fatalf("write large: %v", err)
	}

	got, err := InspectStreams(root)
	if err != nil {
		t.Fatalf("InspectStreams: %v", err)
	}
	if filepath.Base(got.File) != "00002.m2ts" {
		t.Errorf("File = %q, want the largest stream 00002.m2ts", got.File)
	}
}

func TestHasAACSDir(t *testing.T) {
	withAACS := writeDisc(t, buildM2TS(20, 0), true)
	if !HasAACSDir(withAACS) {
		t.Error("HasAACSDir = false for a disc with an AACS directory")
	}

	withoutAACS := writeDisc(t, buildM2TS(20, 0), false)
	if HasAACSDir(withoutAACS) {
		t.Error("HasAACSDir = true for a disc with no AACS directory")
	}
}
