name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.1001

      - name: Generate templ files
        run: templ generate

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -race
